id: P004188
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:59:25.374654
source_metadata:
  id: bdr:W4CZ294453
  title: ཡུམ་ཀའི་གསང་སྒྲུབ་སེངྒེའི་གདོང་ཅན་གྱི་སྐོར།
  author: ''
  volumes:
    32db376c8de34e3ebc7dd5a0902124fe:
      image_group_id: I4CZ294579
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
